feat: support secrets in render task definition
aws-actions/amazon-ecs-render-task-definition pull request #152
Opened 2022-01-26 14:45 UTC by yehudacohen

*Issue #, if available:*
#20 
*Description of changes:*
Add ability to add secrets to task definition. There is already a pull request here #143 which tries to do this, but it isn't backward compatible. This pull request is. It also doesn't add tests which this PR does.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-04-26 22:29 UTC, kroehre commented
👍 we'd love to use this feature. What's blocking?

2023-11-06 13:12 UTC, cairesvs commented
Hi 👋 Any updates about when this will be merged? I think it's a needed feature 🙏

2024-03-28 11:57 UTC, canhassancode commented
Hi there, any update on this?

2024-05-10 18:52 UTC, amazreech commented
Hi, thank you so much for your contribution. Apologies on the delay. 
We will be working on reviewing Pull Requests on the repository. In the mean time please ensure that below steps, if not already done, are taken care of in your PR:

1. Verify if PR follows semantic pull request [conventions](https://www.conventionalcommits.org/en/v1.0.0/#specification).

2. Please be sure to run `npm run package` command to update **dist/** folder with latest  dependencies.

3. Resolve merge conflicts on the PR if any.

2024-06-20 19:03 UTC, nickddowns approved these changes

2024-08-29 22:14 UTC, banthaherder commented
@yehudacohen great work on this! Looks like it is approved just need a quick fix for merge conflicts. Can't wait to use this 🙌

2024-09-24 09:04 UTC, aminzar-access commented
Any updates on this? Cheers!

2024-09-24 16:14 UTC, pratikgedia commented
@karanbokil Would you be able to help to get this merged in / reviewed ?

2024-09-24 17:44 UTC, amazreech requested changes

2024-09-24 17:44 UTC, amazreech commented on index.js
> +        // If environment array is missing, create it
Comment Needs Update, from `environment array` to `secrets array`

2024-09-24 17:44 UTC, amazreech commented on index.js
> +          }
Ideally, this (Lines 80 to Lines 91, I think) could be transferred to a common method as we are using same set of code when fetching `environmentVariables` as well.

2024-09-24 17:44 UTC, amazreech commented on index.js
> +
nit: unnecessary extra line

2024-09-24 17:44 UTC, amazreech commented on index.test.js
> +    test('renders a task definition at an absolute path, and with initial environment and secrets empty', async () => {
__nit:__ I might have understood this wrong and I see that the naming was always this way but the test name here is not accurate as the secrets and environment provided is not empty?

2024-09-27 06:46 UTC, pt-vamshi commented
waiting for this feature

2024-09-30 14:16 UTC, amazreech approved these changes

2024-10-03 19:52 UTC, kg-aws commented
Hi - We have made a follow up PR #334 to fix the merge issues. We have unforgettably added the original authors to that PR. Closing this PR.

https://github.com/aws-actions/amazon-ecs-render-task-definition/pull/334

2024-10-03 19:52 UTC, closed without merging